apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

commonLabels:
  app: hello-world

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: duytran410/hello-world
    newTag: latest
