apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: visitor-counter-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 100Mi
