apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: visitor-counter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Anh-Duy-Tran/home-server-gitops.git
    path: apps/visitor-counter/manifests
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
