apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

commonLabels:
  app: photobook

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: duytran410/photobook
    newTag: v20251019-070418-adf4e0e
