apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - prometheus-deployment.yaml
  - grafana-deployment.yaml

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml=configs/prometheus.yml
  - name: grafana-datasources
    files:
      - datasources.yaml=configs/datasources.yaml

images:
  - name: prom/prometheus
    newTag: v2.54.1
  - name: grafana/grafana
    newTag: "11.3.0"

replicas:
  - name: prometheus
    count: 1
  - name: grafana
    count: 1

commonLabels:
  app.kubernetes.io/part-of: monitoring-stack
  managed-by: argocd
