apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://k8s-at-home.com/charts/
    targetRevision: 5.5.2
    chart: adguard-home
    helm:
      values: |
        image:
          repository: adguard/adguardhome
          tag: latest

        env:
          TZ: UTC

        service:
          main:
            type: ClusterIP
            ports:
              http:
                port: 3000

          dns-https:
            enabled: true
            type: ClusterIP
            ports:
              dns-https:
                enabled: true
                port: 443
                protocol: TCP
                targetPort: 3000

          dns-tcp:
            enabled: true
            type: NodePort
            ports:
              dns-tcp:
                enabled: true
                port: 53
                protocol: TCP
                targetPort: 53
                nodePort: 30053

          dns-udp:
            enabled: true
            type: NodePort
            ports:
              dns-udp:
                enabled: true
                port: 53
                protocol: UDP
                targetPort: 53
                nodePort: 30053

        ingress:
          main:
            enabled: true
            ingressClassName: traefik
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: web
            hosts:
              - host: dns.duytran.app
                paths:
                  - path: /dns-query
                    pathType: Prefix

        persistence:
          config:
            enabled: true
            type: pvc
            storageClass: openebs-hostpath
            size: 1Gi
            accessMode: ReadWriteOnce
          data:
            enabled: true
            type: pvc
            storageClass: openebs-hostpath
            size: 5Gi
            accessMode: ReadWriteOnce

        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: stateful-apps

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
