apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-library-pvc
  namespace: calibre
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: openebs-hostpath
