apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-ray
  namespace: stateful-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-ray
  template:
    metadata:
      labels:
        app: jupyter-ray
    spec:
      containers:
        - name: jupyter
          image: rayproject/ray:nightly-aarch64
          command: ["/bin/bash", "-c"]
          args:
            - |
              pip install jupyterlab
              jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
          ports:
            - containerPort: 8888
              name: jupyter
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
          env:
            - name: RAY_ADDRESS
              value: "ray://raycluster-sample-head-svc.ray-system.svc.cluster.local:10001"
          volumeMounts:
            - name: notebooks
              mountPath: /home/ray
      volumes:
        - name: notebooks
          persistentVolumeClaim:
            claimName: jupyter-notebooks
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-notebooks
  namespace: stateful-apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: openebs-hostpath
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-ray
  namespace: stateful-apps
spec:
  selector:
    app: jupyter-ray
  ports:
    - port: 8888
      targetPort: 8888
      name: jupyter
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jupyter-ray-netpol
  namespace: stateful-apps
spec:
  podSelector:
    matchLabels:
      app: jupyter-ray
  policyTypes:
    - Egress
  egress:
    # Allow all egress for pip installs and cross-namespace Ray connections
    - {}
