apiVersion: v1
kind: Namespace
metadata:
  name: ray-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-ray
  namespace: ray-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-ray
  template:
    metadata:
      labels:
        app: jupyter-ray
    spec:
      containers:
        - name: jupyter
          image: rayproject/ray:nightly-aarch64
          command: ["/bin/bash", "-c"]
          args:
            - |
              pip install jupyterlab
              jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
          ports:
            - containerPort: 8888
              name: jupyter
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
          env:
            - name: RAY_ADDRESS
              value: "ray://raycluster-sample-head-svc:10001"
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-ray
  namespace: ray-system
spec:
  selector:
    app: jupyter-ray
  ports:
    - port: 8888
      targetPort: 8888
      name: jupyter
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jupyter-ray-netpol
  namespace: ray-system
spec:
  podSelector:
    matchLabels:
      app: jupyter-ray
  policyTypes:
    - Egress
  egress:
    # Allow DNS resolution
    - to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
      ports:
        - protocol: UDP
          port: 53
    # Allow connection to Ray cluster only
    - to:
        - podSelector:
            matchLabels:
              ray.io/cluster: raycluster-sample
      ports:
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 10001
        - protocol: TCP
          port: 8265
