apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: raycluster-sample
  namespace: ray-system
spec:
  rayVersion: "2.50.1"
  headGroupSpec:
    rayStartParams:
      metrics-export-port: "8080"
    template:
      metadata:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "8080"
          prometheus.io/path: "/metrics"
      spec:
        containers:
          - name: ray-head
            image: rayproject/ray:2.50.1-py311-gpu
            lifecycle:
              postStart:
                exec:
                  command:
                    [
                      "/bin/bash",
                      "-c",
                      "pip install --user scikit-learn xgboost pandas pyarrow s3fs fsspec IPython ipykernel minio",
                    ]
            resources:
              limits:
                cpu: "2"
                memory: "5Gi"
              requests:
                cpu: "1"
                memory: "4Gi"
            ports:
              - containerPort: 6379
                name: gcs-server
              - containerPort: 8265
                name: dashboard
              - containerPort: 10001
                name: client
              - containerPort: 8080
                name: metrics
  workerGroupSpecs:
    - replicas: 4
      minReplicas: 4
      maxReplicas: 4
      groupName: small-group
      rayStartParams:
        metrics-export-port: "8080"
      template:
        metadata:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "8080"
            prometheus.io/path: "/metrics"
        spec:
          containers:
            - name: ray-worker
              image: rayproject/ray:2.50.1-py311-gpu
              lifecycle:
                postStart:
                  exec:
                    command:
                      [
                        "/bin/bash",
                        "-c",
                        "pip install --user scikit-learn xgboost pandas pyarrow s3fs fsspec IPython ipykernel minio",
                      ]
              resources:
                limits:
                  cpu: "2"
                  memory: "4Gi"
                requests:
                  cpu: "1"
                  memory: "3Gi"
              ports:
                - containerPort: 8080
                  name: metrics
