apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: raycluster-sample
  namespace: ray-system
spec:
  rayVersion: "2.50.1"
  headGroupSpec:
    rayStartParams: {}
    template:
      spec:
        containers:
          - name: ray-head
            image: rayproject/ray:2.50.1-py311-gpu
            resources:
              limits:
                cpu: "2"
                memory: "4Gi"
              requests:
                cpu: "1"
                memory: "2Gi"
            ports:
              - containerPort: 6379
                name: gcs-server
              - containerPort: 8265
                name: dashboard
              - containerPort: 10001
                name: client
  workerGroupSpecs:
    - replicas: 4
      minReplicas: 2
      maxReplicas: 6
      groupName: small-group
      rayStartParams: {}
      template:
        spec:
          containers:
            - name: ray-worker
              image: rayproject/ray:2.50.1-py311-gpu
              resources:
                limits:
                  cpu: "2"
                  memory: "1Gi"
                requests:
                  cpu: "1"
                  memory: "512Mi"
