apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ray
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Anh-Duy-Tran/home-server-gitops.git # Update with your repo
    targetRevision: main
    path: apps/ray
    directory:
      include: "{operator,cluster}.yaml"

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
