apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ray-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" # Apply after wave 0 (the operator)
spec:
  project: default

  source:
    repoURL: https://github.com/your-repo/PersonalCloud.git # Update with your repo
    targetRevision: main
    path: apps/ray/manifests
    directory:
      include: ray-cluster-sample.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: ray-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
