name: Hello World CI/CD

on:
  push:
    branches: [main]
    paths:
      - "apps/hello-world/src/**"
      - "apps/hello-world/Dockerfile"
      - ".github/workflows/hello-world.yml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/docker-build.yml
    with:
      app_name: hello-world
      app_path: apps/hello-world
      docker_username: ${{ secrets.DOCKER_USERNAME }}
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: build
    uses: ./.github/workflows/update-manifest.yml
    with:
      manifest_path: apps/hello-world/manifests/deployment.yaml
      image_name: ${{ needs.build.outputs.image_name }}
      image_tag: ${{ needs.build.outputs.image_tag }}
