name: Update Kustomization

on:
  workflow_call:
    inputs:
      kustomization_path:
        required: true
        type: string
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update kustomization
        run: |
          sed -i "s|newTag:.*|newTag: ${{ inputs.image_tag }}|g" ${{ inputs.kustomization_path }}
          echo "Updated kustomization:"
          grep -A2 "images:" ${{ inputs.kustomization_path }}

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ inputs.kustomization_path }}
          git diff --staged --quiet || (
            git commit -m "ci: update image to ${{ inputs.image_tag }}" &&
            git push
          )
