name: Update Manifest

on:
  workflow_call:
    inputs:
      manifest_path:
        required: true
        type: string
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update manifest
        run: |
          sed -i "s|image: .*/$(basename ${{ inputs.image_name }}):.*|image: ${{ inputs.image_name }}:${{ inputs.image_tag }}|g" ${{ inputs.manifest_path }}
          echo "Updated manifest:"
          grep "image:" ${{ inputs.manifest_path }}

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ inputs.manifest_path }}
          git diff --staged --quiet || (
            git commit -m "ci: update image to ${{ inputs.image_tag }}" &&
            git push
          )
